---@class x11.xi2.ffi.RawEvent: ffi.cdata*
---@field type number
---@field evtype x11.xi2.EventType
---@field deviceid number
---@field sourceid number
---@field detail number
---@field flags number
---@field time number
---@field valuators { mask_len: number, mask: ffi.cdata*, values: ffi.cdata* }
---@field raw_values ffi.cdata*
